name: add_admin_label_function
description: Appwrite function to add 'admin' label to a user.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust based on your Dart SDK version

dependencies:
  dart_appwrite: ^11.0.0 # Use the latest appropriate version compatible with server-side

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0